#cloud-config
users:
  - name: "{{ mws_compute_vm_ssh_username }}"
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) PASSWD:ALL'
    ssh_authorized_keys:
      - {{ mws_compute_vm_ssh_public_key | default('') }}

package_update: true
package_upgrade: true
packages:
  - htop
  - vim
  - curl
  - wget
  - net-tools